# Generated by Django 6.0.4 on 2026-05-04 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mcqquestion_mcqoption_theoryquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoryquestion',
            name='school_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schoollevel'),
        ),
        migrations.AlterField(
            model_name='theoryquestion',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.level'),
        ),
    ]
