# Generated by Django 6.0.6 on 2026-07-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mcqquestion_school_level_alter_mcqquestion_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
