# Generated by Django 6.0.6 on 2026-07-05 23:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_programdetails_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHSStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True, help_text='Comma-separated strengths profile')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective')], default='ELECTIVE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlternativePathway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pathway_type', models.CharField(choices=[('MATURE', 'Mature Entry (25+)'), ('HND_DIPLOMA', 'HND / Diploma Holders'), ('ACCESS', 'Access Course'), ('INTERNATIONAL', 'International Credentials')], max_length=20)),
                ('description', models.TextField(help_text='Requirements and process')),
                ('is_active', models.BooleanField(default=True)),
                ('program_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_pathways', to='core.programdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramAdmissionTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier_name', models.CharField(default='Regular', max_length=50)),
                ('cutoff_aggregate', models.IntegerField(help_text='Max WASSCE aggregate allowed')),
                ('gender', models.CharField(choices=[('ANY', 'Any'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='ANY', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('program_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_tiers', to='core.programdetails')),
            ],
            options={
                'unique_together': {('program_details', 'tier_name', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='SHSStreamSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_core', models.BooleanField(default=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.shsstream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('stream', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ProgramPrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_level', models.CharField(choices=[('REQ', 'Required'), ('PRE', 'Preferred'), ('NIC', 'Nice to have')], default='REQ', max_length=3)),
                ('min_grade', models.IntegerField(default=6, help_text='WAEC scale: 1=A1 … 6=C6 (lower is better)')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='core.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('program', 'subject')},
            },
        ),
    ]
