# Generated by Django 6.0.6 on 2026-07-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_planfeature_planfeaturethrough_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='color',
            field=models.CharField(default='#1e3a5f', help_text='Hex color for plan branding (e.g. #1e3a5f)', max_length=7),
        ),
    ]
