# Generated by Django 6.0.6 on 2026-07-09 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subscriptionplan_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paystack_public_key', models.CharField(blank=True, help_text='Live Paystack public key', max_length=255)),
                ('paystack_secret_key', models.CharField(blank=True, help_text='Live Paystack secret key (keep secret)', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
