# Generated by Django 6.0.6 on 2026-08-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_useractivity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_subject_name_category'),
        ),
    ]
