# Generated by Django 6.0.6 on 2026-08-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_practicesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='theoryquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
