# Generated by Django 6.0.6 on 2026-08-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mcqquestion_is_active_theoryquestion_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='How many days a paid subscription lasts before expiry'),
        ),
    ]
