# Generated by Django 6.0.6 on 2026-08-18 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_subscriptionplan_duration_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='Primary login identifier', max_length=20, unique=True)),
                ('master_pin_hash', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TermReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term_number', models.PositiveIntegerField(default=1)),
                ('grades', models.JSONField(default=dict, help_text='Map of {subject_name: WAEC grade value 1-9}')),
                ('aggregate', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shsstream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-term_number'],
                'unique_together': {('user', 'term_number')},
            },
        ),
    ]
