# Generated by Django 6.0.6 on 2026-08-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_termreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sms_api_key',
            field=models.CharField(blank=True, help_text='SMS provider API key / token', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_api_url',
            field=models.CharField(blank=True, help_text='Custom API endpoint (for custom provider)', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_provider',
            field=models.CharField(blank=True, choices=[('termii', 'Termii'), ('twilio', 'Twilio'), ('custom', 'Custom HTTP API')], help_text='SMS provider for OTP delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_sender_id',
            field=models.CharField(blank=True, help_text='Sender ID (e.g. EduPath)', max_length=50),
        ),
    ]
