# Generated by Django 6.0.6 on 2026-08-18 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sitesettings_sms_api_key_sitesettings_sms_api_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.shsstream'),
        ),
        migrations.AlterUniqueTogether(
            name='termreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='termreport',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SHS 1'), (2, 'SHS 2'), (3, 'SHS 3')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termreport',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2')], default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='termreport',
            name='term_number',
        ),
        migrations.AlterUniqueTogether(
            name='termreport',
            unique_together={('user', 'year', 'term')},
        ),
        migrations.AlterModelOptions(
            name='termreport',
            options={'ordering': ['-year', '-term']},
        ),
    ]
